version: "3.2"
services:
  flask:
    build: ./flaskapp
    image: kaw393939/flask:latest
    container_name: python
    restart: always
    environment:
      - APP_NAME=flask
      - PYTHONPATH=/home/myuser
    expose:
      - 8080
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./flaskapp:/home/myuser
  nginx:
    image: kaw393939/nginx:latest
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
